name: My First GitHub Action
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # steps는 반드시 특정 job(여기선 build) 안에 포함되어야 합니다!
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple test
        run: |
          echo "현재 폴더의 파일 목록을 확인합니다:"
          ls -R